server:
  port: 8430

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8600/eureka/

# management:
#   endpoints:
#     web:
#       base-path: /especiesmonitor
#       exposure:
#         include: "*"
#   endpoint:
#     health:
#       show-details: ALWAYS

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/distparse?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #    url: jdbc:mysql://39.96.193.166:3306/zoology_one?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    #    password: zm@615_2019
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  admin:
    discovery.converter.management-context-path: /especiesmonitor
  application:
    name: protect-web
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  thymeleaf:
    cache: false
  #  zipkin:
  #    base-url: http://localhost:9411
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8


feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 60000




